import { pgTable, uuid, varchar, text, jsonb, boolean, timestamp, date, index, foreignKey } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { organizationsTable } from './organizations';

export const reportsTable = pgTable(
  'reports',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id').notNull(),
    title: varchar('title', { length: 255 }).notNull(),
    reportMonth: date('report_month').notNull(),
    fileUrl: varchar('file_url', { length: 500 }),
    fileName: varchar('file_name', { length: 255 }),
    fileSize: varchar('file_size', { length: 50 }),
    keyMetrics: jsonb('key_metrics'),
    recommendations: jsonb('recommendations'),
    isAutoGenerated: boolean('is_auto_generated').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    orgIdFk: foreignKey({
      columns: [table.organizationId],
      foreignColumns: [organizationsTable.id],
      name: 'reports_organization_id_fk',
    }).onDelete('cascade'),
    orgIdIdx: index('reports_organization_id_idx').on(table.organizationId),
    reportMonthIdx: index('reports_report_month_idx').on(table.reportMonth),
  }),
);

export const reportsRelations = relations(reportsTable, ({ one }) => ({
  organization: one(organizationsTable, {
    fields: [reportsTable.organizationId],
    references: [organizationsTable.id],
  }),
}));

export type Report = typeof reportsTable.$inferSelect;
export type NewReport = typeof reportsTable.$inferInsert;
