import { NextRequest } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { db } from '@/db';
import {
  organizationsTable,
  organizationMembersTable,
  usersTable,
  reportsTable,
} from '@/db/schema';
import { eq, desc } from 'drizzle-orm';
import { z } from 'zod';
import {
  jsonResponse,
  errorResponse,
  unauthorizedResponse,
  forbiddenResponse,
  validateRequest,
} from '@/lib/api-helpers';

async function resolveContext(clerkUserId: string, clerkOrgId: string | null) {
  const userRows = await db
    .select({ id: usersTable.id, role: usersTable.role })
    .from(usersTable)
    .where(eq(usersTable.clerkUserId, clerkUserId))
    .limit(1);
  const dbUser = userRows[0] ?? null;
  if (!dbUser) return { org: null, dbUser: null };

  if (clerkOrgId) {
    const orgRows = await db
      .select()
      .from(organizationsTable)
      .where(eq(organizationsTable.clerkOrgId, clerkOrgId))
      .limit(1);
    if (orgRows[0]) return { org: orgRows[0], dbUser };
  }

  const memberRows = await db
    .select({ organizationId: organizationMembersTable.organizationId })
    .from(organizationMembersTable)
    .where(eq(organizationMembersTable.userId, dbUser.id))
    .limit(1);
  if (!memberRows[0]) return { org: null, dbUser };

  const orgRows = await db
    .select()
    .from(organizationsTable)
    .where(eq(organizationsTable.id, memberRows[0].organizationId))
    .limit(1);
  return { org: orgRows[0] ?? null, dbUser };
}

export async function GET(_request: NextRequest) {
  try {
    const { userId: clerkUserId, orgId: clerkOrgId } = await auth();
    if (!clerkUserId) return unauthorizedResponse();

    const { org } = await resolveContext(clerkUserId, clerkOrgId ?? null);
    if (!org) return errorResponse('Organization not found', 404);

    const reports = await db
      .select()
      .from(reportsTable)
      .where(eq(reportsTable.organizationId, org.id))
      .orderBy(desc(reportsTable.reportMonth));

    return jsonResponse(reports);
  } catch (err) {
    console.error('GET /api/reports error:', err);
    return errorResponse('Internal server error', 500);
  }
}

const CreateReportSchema = z.object({
  title: z.string().min(1).max(255),
  reportMonth: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Must be YYYY-MM-DD'),
  fileUrl: z.string().url().optional(),
  fileName: z.string().max(255).optional(),
  fileSize: z.string().max(50).optional(),
  keyMetrics: z.record(z.unknown()).optional(),
  recommendations: z.array(z.string()).optional(),
  isAutoGenerated: z.boolean().optional(),
});

export async function POST(request: NextRequest) {
  try {
    const { userId: clerkUserId, orgId: clerkOrgId } = await auth();
    if (!clerkUserId) return unauthorizedResponse();

    const { org, dbUser } = await resolveContext(clerkUserId, clerkOrgId ?? null);
    if (!org || !dbUser) return forbiddenResponse();

    // Only CWS admins can create reports
    if (dbUser.role !== 'admin') return forbiddenResponse();

    const body = await request.json();
    const validation = validateRequest<z.infer<typeof CreateReportSchema>>(CreateReportSchema, body);
    if (!validation.success) {
      return errorResponse(validation.error ?? 'Validation failed', 400);
    }

    const data = validation.data!;
    const [report] = await db
      .insert(reportsTable)
      .values({
        organizationId: org.id,
        title: data.title,
        reportMonth: data.reportMonth,
        fileUrl: data.fileUrl,
        fileName: data.fileName,
        fileSize: data.fileSize,
        keyMetrics: data.keyMetrics ?? null,
        recommendations: data.recommendations ?? null,
        isAutoGenerated: data.isAutoGenerated ?? false,
      })
      .returning();

    return jsonResponse(report, 201);
  } catch (err) {
    console.error('POST /api/reports error:', err);
    return errorResponse('Internal server error', 500);
  }
}
