"use client";

import { useEffect, useState } from "react";
import { Skeleton } from "@/components/ui/skeleton";
import {
  CalendarDays,
  ExternalLink,
  Loader2,
  FileText,
  AlertCircle,
} from "lucide-react";

// ── Types ──────────────────────────────────────────────────────────────────

interface KeyMetrics {
  visitors?: number;
  newLeads?: number;
  avgPosition?: number;
  gbpCalls?: number;
  [key: string]: unknown;
}

interface Report {
  id: string;
  organizationId: string;
  title: string;
  reportMonth: string; // YYYY-MM-DD
  fileUrl: string | null;
  fileName: string | null;
  fileSize: string | null;
  keyMetrics: KeyMetrics | null;
  recommendations: string[] | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

// ── Helpers ────────────────────────────────────────────────────────────────

function formatMonth(dateStr: string): { month: string; year: string } {
  const d = new Date(dateStr + "T00:00:00");
  return {
    month: d.toLocaleDateString("en-US", { month: "long" }),
    year: d.getFullYear().toString(),
  };
}

function getCurrentMonthName(): string {
  return new Date().toLocaleDateString("en-US", { month: "long" });
}

// ── Report Card ────────────────────────────────────────────────────────────

function ReportCard({ report }: { report: Report }) {
  const { month, year } = formatMonth(report.reportMonth);
  const metrics = report.keyMetrics ?? {};

  const badges = [
    { label: "Visitors", value: metrics.visitors },
    { label: "New Leads", value: metrics.newLeads },
    { label: "Avg Position", value: metrics.avgPosition },
    { label: "GBP Calls", value: metrics.gbpCalls },
  ].filter((b) => b.value !== undefined && b.value !== null);

  return (
    <div className="bg-white dark:bg-slate-900 rounded-xl border border-[#ccfbf1] dark:border-slate-700/50 shadow-sm hover:shadow-md hover:border-[#0d9488] dark:hover:border-[#0d9488] transition-all duration-200 p-6 flex flex-col gap-4">
      {/* Month + badges row */}
      <div className="flex items-start justify-between gap-2">
        <div>
          <p className="text-2xl font-bold text-slate-900 dark:text-white leading-none">
            {month}
          </p>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            {year}
          </p>
        </div>
        {report.isAutoGenerated && (
          <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-blue-100 dark:bg-slate-800/40 text-[#0d9488] dark:text-[#2563eb] border border-[#99f6e4] dark:border-slate-700 whitespace-nowrap">
            <span className="w-1.5 h-1.5 rounded-full bg-[#2563eb]" />
            Auto-generated
          </span>
        )}
      </div>

      {/* Key metric badges */}
      {badges.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {badges.map(({ label, value }) => (
            <div
              key={label}
              className="flex flex-col items-center bg-slate-50 dark:bg-slate-800 rounded-lg px-3 py-2 min-w-[72px]"
            >
              <span className="text-base font-bold text-slate-900 dark:text-white tabular-nums">
                {typeof value === "number" ? value.toLocaleString() : String(value)}
              </span>
              <span className="text-[10px] text-slate-500 dark:text-slate-400 mt-0.5">
                {label}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* View button */}
      <div className="mt-auto">
        {report.fileUrl ? (
          <a
            href={report.fileUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-[#1d4ed8] hover:bg-[#1d4ed8] text-white text-sm font-medium transition-colors w-full justify-center"
          >
            <ExternalLink className="w-4 h-4" />
            View Report
          </a>
        ) : (
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-500 text-sm font-medium w-full justify-center cursor-not-allowed">
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating...
          </div>
        )}
      </div>
    </div>
  );
}

function ReportCardSkeleton() {
  return (
    <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6 space-y-4">
      <div className="space-y-2">
        <Skeleton className="h-7 w-36" />
        <Skeleton className="h-4 w-12" />
      </div>
      <div className="flex gap-2">
        {[...Array(4)].map((_, i) => (
          <Skeleton key={i} className="h-14 w-16 rounded-lg" />
        ))}
      </div>
      <Skeleton className="h-9 w-full rounded-lg" />
    </div>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────

export function ReportsArchive() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch("/api/reports");
        if (!res.ok) throw new Error("Failed to load reports");
        const json = await res.json();
        setReports(json.data ?? []);
      } catch {
        setError("Failed to load reports. Please try again.");
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  if (loading) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {[...Array(6)].map((_, i) => (
          <ReportCardSkeleton key={i} />
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center space-y-4">
        <AlertCircle className="w-10 h-10 text-red-400" />
        <p className="text-sm text-slate-500 dark:text-slate-400">{error}</p>
      </div>
    );
  }

  if (reports.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center space-y-4">
        <div className="w-16 h-16 rounded-full bg-blue-100 dark:bg-slate-800/30 flex items-center justify-center">
          <CalendarDays className="w-8 h-8 text-[#2563eb]" />
        </div>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
          No reports yet
        </h3>
        <p className="text-sm text-slate-500 dark:text-slate-400 max-w-sm">
          Your first monthly report will be ready at the end of{" "}
          {getCurrentMonthName()}.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
        <FileText className="w-4 h-4" />
        <span>
          {reports.length} report{reports.length !== 1 ? "s" : ""} available
        </span>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {reports.map((report) => (
          <ReportCard key={report.id} report={report} />
        ))}
      </div>
    </div>
  );
}
