import { db } from "@/db";
import { reportsTable } from "@/db/schema";
import { eq, and, desc } from "drizzle-orm";

export async function getReports(orgId: string) {
  const result = await db
    .select()
    .from(reportsTable)
    .where(eq(reportsTable.organizationId, orgId))
    .orderBy(desc(reportsTable.reportMonth));

  return result;
}

export async function getReport(id: string) {
  const result = await db
    .select()
    .from(reportsTable)
    .where(eq(reportsTable.id, id))
    .limit(1);

  return result?.[0] || null;
}

export async function createReport(data: {
  organizationId: string;
  period?: string;
  startDate?: Date;
  endDate?: Date;
  metrics?: Record<string, any>;
  summary?: string;
  fileUrl?: string;
  title?: string;
}) {
  const reportMonth = data.startDate
    ? data.startDate.toISOString().split('T')[0]!
    : new Date().toISOString().split('T')[0]!;

  const result = await db
    .insert(reportsTable)
    .values({
      organizationId: data.organizationId,
      title: data.title || `Report ${reportMonth}`,
      reportMonth,
      fileUrl: data.fileUrl,
      keyMetrics: data.metrics || null,
      isAutoGenerated: false,
    })
    .returning();

  return result?.[0] || null;
}

export async function getLatestReport(orgId: string, period?: string) {
  const result = await db
    .select()
    .from(reportsTable)
    .where(eq(reportsTable.organizationId, orgId))
    .orderBy(desc(reportsTable.reportMonth))
    .limit(1);

  return result?.[0] || null;
}
